### ISSUE TITLE
mgos_wifi.h:122:6: error: use of enum 'mgos_wifi_status' without previous declaration  enum mgos_wifi_status mgos_wifi_get_status(void);

### ISSUE THREAD

**Issue by gpepe** [mongoose-os-libs/wifi#15]
mgos/esp32-build                 3.0-r11 

libs:
  - origin: https://github.com/mongoose-os-libs/rpc-service-config
  - origin: https://github.com/mongoose-os-libs/rpc-service-fs
  - origin: https://github.com/mongoose-os-libs/rpc-service-wifi
  - origin: https://github.com/mongoose-os-libs/rpc-uart
  - origin: https://github.com/mongoose-os-libs/http-server

deps/wifi/include/mgos_wifi.h:122:6: error: use of enum 'mgos_wifi_status' without previous declaration
 enum mgos_wifi_status mgos_wifi_get_status(void);

Using port /dev/ttyUSB0
Getting configuration...
Error: no config value at path "wifi.sta.ssid"

**Comment by rojer** [comment]
fixed by https://github.com/mongoose-os-libs/wifi/commit/7e9abf0635897748f082bf18eef22a3815b78c65
