### ISSUE TITLE
Implement mgos_wifi_rssi() and/or _signal()

### ISSUE THREAD

**Issue by pimvanpelt** [mongoose-os-libs/wifi#3]
Hoi,

For portable mongoose applications, it can be useful to report on WiFi RSSI and signal strength. For some targets (notably ESP32 and ESP8266), I know how to do this:

```c
// ESP32
int8_t mgos_wifi_rssi() {
  wifi_ap_record_t info;
  if(0 != esp_wifi_sta_get_ap_info(&info))
    return 0;
  else
    return info.rssi;
}

// ESP8266
int8_t mgos_wifi_rssi() {
  return wifi_station_get_rssi();
}
```

Turning RSSI into signal strength looks something like:
```c
uint8_t mgos_wifi_signal_strength(int8_t rssi) {  
  if(rssi <= -100)
    return 0;
  if (rssi >= -50)
    return 100;
  return 2 * (rssi + 100);
}
```

Not entirely sure how to do this in CC3200 and CC3220, but perhaps you have a pointer. Happy to submit a PR if you think this is a good addition to the `wifi` module.

**Comment by rojer** [comment]
easy enough, done. PR sent.
