### ISSUE TITLE
Scan never returns if both AP and STA are disabled initially on ESP32

### ISSUE THREAD

**Issue by kzyapkov** [mongoose-os-libs/wifi#39]
To reproduce, run an `empty` app on an ESP32 with wifi.ap.enable=false and wifi.sta.enable=false. For easier testing, also include the `rpc-service-wifi` library. Calling `Wifi.Scan` usually works the first time it is called after a reboot, but every subsequent invocation never receives a response. No callbacks seem to be invoked by the underlying SDK for scan result or completion.

`Wifi.Scan` can be called over UART, GATTS or Ethernet.

We initially noticed this while using GATTS, and the suspicion was that BT+Wifi was causing issues. However, it seems reproducible even without BT enabled. I also recently revived [this](https://github.com/kzyapkov/mos-ble) tool to make testing over rpc-gatts possible.

**Comment by rojer** [comment]
thanks Kiril! reproduced and fixed
